// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock, ReferencePage } from "emdash";

export interface AuditEvent {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  action: string;
  subject_type: string;
  subject_slug: string;
  field?: string;
  before?: string;
  after?: string;
  reason?: string;
  detail?: string;
  actor_id?: string;
  occurred_at?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Collection {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  tagline?: string;
  summary: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Dispute {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subject_type: string;
  subject_slug: string;
  reason: string;
  state: string;
  detail?: string;
  report_id?: string;
  reporter_id?: string;
  reported_at?: string;
  resolution?: string;
  resolved_at?: string;
  resolved_by?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Example {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  origin: string;
  media_kind: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  specimen?: string;
  rights_status: string;
  rights_note?: string;
  note?: string;
  source_url?: string;
  source_repo?: string;
  source_ref?: string;
  source_path?: string;
  licence_spdx?: string;
  licence_evidence?: string;
  attribution?: string;
  content_hash?: string;
  technical?: unknown;
  downloadable?: boolean;
  featured?: boolean;
  dispute_state?: string;
  dispute_reason?: string;
  dispute_note?: string;
  dispute_reported_at?: string;
  dispute_resolved_at?: string;
  source_id?: string;
  source_revision?: string;
  source_hash?: string;
  machine_synced_at?: string;
  visibility?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Exclusion {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  scope: string;
  match: string;
  reason?: string;
  detail?: string;
  state: string;
  dispute_slug?: string;
  recorded_at?: string;
  recorded_by?: string;
  lifted_at?: string;
  lifted_by?: string;
  lift_reason?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Possibility {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  tagline?: string;
  summary: string;
  technique: string;
  vertical: string;
  media_kind: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  specimen?: string;
  representative_origin: string;
  rights_status: string;
  rights_note?: string;
  build_notes?: string;
  prompt_scaffold?: string;
  example_count?: number;
  distinct_sources?: number;
  novelty?: number;
  coverage?: number;
  editorial_rank?: number;
  featured?: boolean;
  source_hunt?: string;
  source_ids?: string;
  source_revision?: string;
  machine_synced_at?: string;
  visibility?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Rating {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subject_type: string;
  subject_slug: string;
  stars: number;
  user_id: string;
  user_email?: string;
  signal: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Report {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subject_type: string;
  subject_slug: string;
  reason: string;
  detail?: string;
  user_id?: string;
  user_email?: string;
  resolution?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface CollectionReferences {
  members: ReferencePage<Possibility>;
}

export interface ExampleReferences {
  possibility: ReferencePage<Possibility>;
}

declare module "emdash" {
  interface EmDashCollections {
    audit_events: AuditEvent;
    collections: Collection;
    disputes: Dispute;
    examples: Example;
    exclusions: Exclusion;
    pages: Page;
    possibilities: Possibility;
    ratings: Rating;
    reports: Report;
  }
  interface EmDashCollectionReferences {
    collections: CollectionReferences;
    examples: ExampleReferences;
  }
}