// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock, ReferencePage } from "emdash";

export interface Collection {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  tagline?: string;
  summary: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Example {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  origin: string;
  media_kind: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  specimen?: string;
  rights_status: string;
  rights_note?: string;
  note?: string;
  source_url?: string;
  source_repo?: string;
  source_ref?: string;
  source_path?: string;
  licence_spdx?: string;
  licence_evidence?: string;
  attribution?: string;
  content_hash?: string;
  technical?: unknown;
  downloadable?: boolean;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Possibility {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  tagline?: string;
  summary: string;
  technique: string;
  vertical: string;
  media_kind: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  specimen?: string;
  representative_origin: string;
  rights_status: string;
  rights_note?: string;
  build_notes?: string;
  prompt_scaffold?: string;
  example_count?: number;
  distinct_sources?: number;
  novelty?: number;
  coverage?: number;
  editorial_rank?: number;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface CollectionReferences {
  members: ReferencePage<Possibility>;
}

export interface ExampleReferences {
  possibility: ReferencePage<Possibility>;
}

declare module "emdash" {
  interface EmDashCollections {
    collections: Collection;
    examples: Example;
    pages: Page;
    possibilities: Possibility;
  }
  interface EmDashCollectionReferences {
    collections: CollectionReferences;
    examples: ExampleReferences;
  }
}