/**
 * Every committed brand asset, declared once.
 *
 * The generator (`scripts/build-brand.mjs`) writes this list, `npm run
 * brand:check` verifies it, and `tests/brand.test.ts` asserts the files still
 * match. Declaring the set here rather than inside the script is what stops the
 * check from being "the generator agrees with itself": a variant that is added
 * to the generator but not to the docs, or vice versa, is a visible diff.
 *
 * File names carry the ink rather than a vague "variant": `mark-ink.svg` is
 * `--ink` on transparency, `mark-compact-canvas.svg` is the icon form in
 * `--canvas`. An asset whose name does not say which ink it is drawn in is an
 * asset somebody has to open to use.
 */
import { MARK_INK, MARK_MIN_SIZE_PX, type MarkDetail } from "./mark.ts";

export interface BrandSvgAsset {
	/** Repository-relative path. */
	file: string;
	/** `aria-label`, and the sentence used in the docs table. */
	label: string;
	/**
	 * `mark` is generated by `markSvg()`. `diagram` is generated by
	 * `clearSpaceSvg()`, which is a document rather than a placement asset and
	 * reads its numbers from the constants instead of taking them as arguments.
	 */
	kind?: "mark" | "diagram";
	detail: MarkDetail;
	ink: string;
	ground?: string;
	/** Intrinsic size; omitted so a kit file scales freely. */
	size?: number;
	/** Held inside Android's maskable safe zone. */
	maskable?: boolean;
	/** Where the variant is meant to be used. Kept short — this is a usage note, not a paragraph. */
	used: string;
}

/** The brand kit. Source assets for anyone placing the identity by hand. */
export const BRAND_SVGS: BrandSvgAsset[] = [
	{
		file: "brand/mark.svg",
		label: "Asset Hunter aperture mark",
		detail: "full",
		ink: MARK_INK.ember,
		size: 24,
		used: "Default export. Ember on transparency, for dark surfaces where the accent is welcome.",
	},
	{
		file: "brand/mark-ink.svg",
		label: "Asset Hunter aperture mark, one ink",
		detail: "full",
		ink: MARK_INK.ink,
		size: 24,
		used: "One-ink reversed for dark backgrounds. This is what the masthead and footer render.",
	},
	{
		file: "brand/mark-canvas.svg",
		label: "Asset Hunter aperture mark, one ink, for light backgrounds",
		detail: "full",
		ink: MARK_INK.canvas,
		size: 24,
		used: "One-ink positive for light and print backgrounds.",
	},
	{
		file: "brand/mark-compact.svg",
		label: "Asset Hunter aperture mark, icon form",
		detail: "compact",
		ink: MARK_INK.ember,
		size: 24,
		used: "Icon form in ember, for anything drawn smaller than 32px on a dark surface.",
	},
	{
		file: "brand/mark-compact-ink.svg",
		label: "Asset Hunter aperture mark, icon form, one ink",
		detail: "compact",
		ink: MARK_INK.ink,
		size: 24,
		used: "Icon form in one ink, for small sizes where the accent would be the loudest thing on screen.",
	},
	{
		file: "brand/mark-compact-canvas.svg",
		label: "Asset Hunter aperture mark, icon form, for light backgrounds",
		detail: "compact",
		ink: MARK_INK.canvas,
		size: 24,
		used: "Icon form in one ink for light backgrounds.",
	},
	{
		file: "brand/mark-maskable.svg",
		label: "Asset Hunter aperture mark, maskable icon",
		detail: "compact",
		ink: MARK_INK.ember,
		ground: MARK_INK.canvas,
		size: 512,
		maskable: true,
		used: "Android maskable icon. The mark is scaled into the safe zone so no launcher mask can crop it.",
	},
	{
		file: "brand/clear-space.svg",
		label: "Asset Hunter mark clear space and minimum size",
		kind: "diagram",
		detail: "full",
		ink: MARK_INK.ember,
		used: "The clear-space and minimum-size diagram. Documentation, not a placement asset.",
	},
];

/**
 * The raster icons, and the one file the browser actually loads.
 *
 * `favicon.svg` is listed here rather than hand-maintained: it was the second
 * copy of the mark, and the copy that had drifted. `brand/check` regenerates
 * it from the same geometry as everything else.
 */
export interface BrandIconAsset {
	file: string;
	/** Width and height in pixels. */
	size: number;
	detail: MarkDetail;
	ink: string;
	ground: string;
	/** Held inside Android's maskable safe zone rather than drawn edge to edge. */
	maskable?: boolean;
	/** Short note for the docs table. */
	used: string;
}

export const BRAND_ICONS: BrandIconAsset[] = [
	{
		file: "public/favicon.svg",
		size: 24,
		detail: "compact",
		ink: MARK_INK.ember,
		ground: MARK_INK.canvas,
		used: "The tab icon. Compact form on the canvas ground, because 16px is where `full` stops working.",
	},
	{
		file: "public/apple-touch-icon.png",
		size: 180,
		detail: "compact",
		ink: MARK_INK.ember,
		ground: MARK_INK.canvas,
		used: "iOS home screen. iOS applies its own mask, so this is opaque and left square for the OS to round.",
	},
	{
		file: "public/icon-192.png",
		size: 192,
		detail: "compact",
		ink: MARK_INK.ember,
		ground: MARK_INK.canvas,
		used: "Installed-app icon. Chrome's install prompt requires a 192px raster.",
	},
	{
		file: "public/icon-512.png",
		size: 512,
		detail: "compact",
		ink: MARK_INK.ember,
		ground: MARK_INK.canvas,
		used: "Installed-app icon. The 512px raster Chrome's install criteria require.",
	},
	{
		file: "public/icon-maskable-512.png",
		size: 512,
		detail: "compact",
		ink: MARK_INK.ember,
		ground: MARK_INK.canvas,
		maskable: true,
		used: "Android maskable icon, mark held inside the safe zone so no launcher mask crops it.",
	},
];

/**
 * Android's maskable safe zone is the circle of diameter 80% of the icon, so a
 * mark drawn edge to edge is cropped by every launcher that masks. The icon
 * form is scaled to 80% of the box and centred, which puts its outermost ink
 * inside that circle with room to spare.
 */
export const MASKABLE_SCALE = 0.8;

/**
 * Smallest size the *full* form is drawn at, re-exported so the manifest and
 * the docs table read the same number the geometry does.
 */
export const FULL_MIN_SIZE_PX = MARK_MIN_SIZE_PX.full;
export const COMPACT_MIN_SIZE_PX = MARK_MIN_SIZE_PX.compact;
